'use client';

import { FormEvent, useState } from 'react';
import apiClient from '@/lib/axios';

const initial = [{ id: 'LR-1024', type: 'Medical leave', dates: '18 Sep – 20 Sep 2026', status: 'Pending' }, { id: 'LR-1019', type: 'Casual leave', dates: '08 Sep 2026', status: 'Approved' }];

export default function LeaveRequestsPage() {
  const [requests, setRequests] = useState(initial);
  const [form, setForm] = useState({ type: 'Casual leave', from: '', to: '', reason: '' });
  const [message, setMessage] = useState('');
  async function submit(e: FormEvent) { e.preventDefault(); if (!form.from || !form.to || !form.reason) return setMessage('Please complete all fields before submitting.'); try { await apiClient.post('/api/leave-requests', { startDate: form.from, endDate: form.to, reason: form.reason }); setMessage('Leave request submitted successfully.'); } catch { setMessage('Request could not be saved. Please try again.'); } setRequests([{ id: `LR-${1025 + requests.length}`, type: form.type, dates: `${form.from} – ${form.to}`, status: 'Pending' }, ...requests]); setForm({ type: 'Casual leave', from: '', to: '', reason: '' }); }
  return <div className="space-y-6"><div><p className="text-xs font-bold uppercase tracking-wider text-emerald-700">Member 2 · Leave management</p><h1 className="mt-2 text-3xl font-bold text-gray-900">Leave requests</h1><p className="mt-2 text-sm text-gray-500">Submit a leave request and track its approval status.</p></div><div className="grid gap-6 xl:grid-cols-[.8fr_1.2fr]"><form onSubmit={submit} className="rounded-2xl border border-white bg-white/80 p-6 shadow-sm"><p className="text-xs font-bold uppercase tracking-wider text-emerald-700">New request</p><h2 className="mt-1 text-xl font-bold">Apply for leave</h2><label className="mt-5 block text-sm font-medium">Leave type<select className="mt-1 w-full rounded-xl border border-gray-200 bg-white px-3 py-2.5 text-sm" value={form.type} onChange={e => setForm({ ...form, type: e.target.value })}><option>Casual leave</option><option>Medical leave</option><option>Emergency leave</option></select></label><div className="mt-4 grid gap-3 sm:grid-cols-2"><label className="text-sm font-medium">From<input className="mt-1 w-full rounded-xl border border-gray-200 px-3 py-2.5 text-sm" type="date" value={form.from} onChange={e => setForm({ ...form, from: e.target.value })} /></label><label className="text-sm font-medium">To<input className="mt-1 w-full rounded-xl border border-gray-200 px-3 py-2.5 text-sm" type="date" value={form.to} onChange={e => setForm({ ...form, to: e.target.value })} /></label></div><label className="mt-4 block text-sm font-medium">Reason<textarea className="mt-1 min-h-24 w-full rounded-xl border border-gray-200 px-3 py-2.5 text-sm" value={form.reason} onChange={e => setForm({ ...form, reason: e.target.value })} /></label><button className="mt-5 w-full rounded-xl bg-emerald-700 px-4 py-3 text-sm font-semibold text-white hover:bg-emerald-800">Submit request</button>{message && <p className="mt-3 text-xs text-gray-500">{message}</p>}</form><section className="rounded-2xl border border-white bg-white/80 p-6 shadow-sm"><p className="text-xs font-bold uppercase tracking-wider text-emerald-700">Request history</p><h2 className="mt-1 text-xl font-bold">Your submissions</h2><div className="mt-5 space-y-3">{requests.map(item => <div key={item.id} className="rounded-xl border border-gray-100 bg-white p-4"><div className="flex items-start justify-between gap-4"><div><p className="text-sm font-semibold">{item.type}</p><p className="mt-1 text-xs text-gray-500">{item.id} · {item.dates}</p></div><span className={`rounded-full px-2.5 py-1 text-xs font-semibold ${item.status === 'Approved' ? 'bg-emerald-50 text-emerald-700' : 'bg-amber-50 text-amber-700'}`}>{item.status}</span></div></div>)}</div></section></div></div>;
}
